### PR TITLE
Update the operator to support the registry viewer

### PR DESCRIPTION
**Pull request by johnmcollier**
Updates the registry operator to support the devfile registry viewer:
- Adds the viewer config json file to the registry config map
- Adds a startupProbe

### CODE REVIEW

**Review by GeekArthur — COMMENTED** [review]
The change looks good to me, please rebase and retest the PR.

**Comment by johnmcollier** [comment]
@GeekArthur Rebased.

**Comment by johnmcollier** [comment]
@GeekArthur Note though that tests will still fail until https://github.com/devfile/registry-support/pull/73 is merged.

**Review by GeekArthur — APPROVED** [review]

**Pull request merged**
