### PR TITLE
Remove CHANGELOG section

### PR DESCRIPTION
**Pull request by michael-valdron**
**Please specify the area for this PR**

documentation

**What does does this PR do / why we need it**:

Since `CHANGELOG.md` no longer exists in favour of using release notes, the section for it should be removed.

**Which issue(s) this PR fixes**:

Fixes #?

**PR acceptance criteria**:

- [x] Test Coverage 
    - Are your changes sufficiently tested, and are any applicable test cases added or updated to cover your changes?
- [x] Gosec scans 
  - Fix all MEDIUM and higher findings and/or annotate a finding per gosec instructions: https://github.com/securego/gosec#annotating-code to address why a finding is not a security issue

Documentation
- [x] Does the registry operator documentation need to be updated with your changes?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by michael-valdron** [comment]
> - [x] Test Coverage 
>     - Are your changes sufficiently tested, and are any applicable test cases added or updated to cover your changes?
> - [x] Gosec scans 
>   - Fix all MEDIUM and higher findings and/or annotate a finding per gosec instructions: https://github.com/securego/gosec#annotating-code to address why a finding is not a security issue

N/A

**Review by thepetk — APPROVED** [review]
/lgtm

**Comment by Jdubrick** [comment]
I'm curious as `CHANGELOG` is going to be required for our CLO Monitor: https://clomonitor.io/docs/topics/checks/#changelog

I suppose we could exempt it and state we are using release notes, but what do you think? @michael-valdron

**Comment by michael-valdron** [comment]
> I'm curious as `CHANGELOG` is going to be required for our CLO Monitor: https://clomonitor.io/docs/topics/checks/#changelog
> 
> I suppose we could exempt it and state we are using release notes, but what do you think? @michael-valdron
> 
> edit: is it possible to leave the changelog section in our readme and link out to release notes?

I agree, lets close this PR to address this separately.

**Comment by michael-valdron** [comment]
> > I'm curious as `CHANGELOG` is going to be required for our CLO Monitor: https://clomonitor.io/docs/topics/checks/#changelog
> > I suppose we could exempt it and state we are using release notes, but what do you think? @michael-valdron
> > edit: is it possible to leave the changelog section in our readme and link out to release notes?
> 
> I agree, lets close this PR to address this separately.

We should address these changes as part of https://github.com/devfile/api/issues/1386

**Pull request closed without merging**
